      double precision inverse_sqrt_pi, pi, square_root_pi, sqrt_ln2,
     &       numerical_zero, numerical_infty
      parameter (
     &          inverse_sqrt_pi = 0.5641895835477563d0, 
     &          pi = 3.141592653589793d0, 
     &          square_root_pi = 1.772453850905516d0, 
     &          sqrt_ln2 = 0.8325546111576977d0,
     &          numerical_zero = 1d-15,
     &          numerical_infty = 4d3)
